spring:
  application:
    name: new-tvds-backend
  datasource:
    url: jdbc:mysql://localhost:3308/new_tvds
    username: root
    password: csu@2024
    druid:
      initial-size: 2
      min-idle: 2

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 45MB
      resolve-lazily: false
  rabbitmq:
    host: 192.168.188.1
    port: 5674
    username: root
    password: csu@2024
  redis:
    host: 192.168.188.1
    password: csu@2024
    port: 6381
common:
  image-type:
    - png
    - jpg
    - jpeg
  rabbitmq:
    component-location-exchange-name: component.location.exchange
    producer-component-location-routing-key: producer.component.location.key
    producer-component-location-queue-name: producer.component.location.queue

http:
  fastapi-url: http://192.168.188.8:3456/api/v1

cluster:
  snowflake:
    worker-id: 0
    datacenter-id: 0


minio:
  endpoint: http://localhost:9000
  access-key: root
  secret-key: csu@2024
  template-image-bucket: new-tvds-component-template-image
  detect-result-bucket: new-tvds-detect-result
  railway-vehicle-bucket: new-tvds-railway-vehicle
server:
  port: 8080
  servlet:
    context-path: /api/v1

jwt:
  secret-key: "NEW-TVDS-CSU-MAKE-SECRET-KEY-ABCDEDGHIJKLMNOPQRSTUVWXYZ" # 请务必在生产环境中更改此密钥！
  expiration-ms: 3600000 # Token 有效期，单位毫秒 (例如：1小时)
  issuer: "New-TVDS-Backend"
  redis-key-prefix: "jwt:auth:" # Redis中存储Token的前缀



